# Generated by Django 3.2.2 on 2021-06-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_fields',
            name='comment_body',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='text_fields',
            name='project_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
